name: 'GithubPagesTemplate'
description: 'Makes it simple to use my preset for Github Pages'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: |
        cd /tmp
        git clone https://github.com/WmeLuna/Pages-Workflow
        mv /tmp/Pages-Workflow/pages/* ${GITHUB_WORKSPACE}/
        cd ${GITHUB_WORKSPACE}/
        ls
      shell: bash
