name: 'GithubPagesTemplate'
description: 'Makes it simple to use my preset for Github Pages'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: |
        git status
        ls
        pwd
      shell: bash
