name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: WmeLuna/Pages-Workflow@main